name: RePublicStorage
version: '1'
main: republicstorage.republicstorage.RePublicStorage
api-version: 1.19
authors: [ SakakiAruka ]
description: public storage (remake)
commands:
  storage:
    permission: storage.default
  storageloads:
    permission: storage.op


permissions:
  storage.default:
    # TODO: rewrite here
    default: op
  storage.op:
    default: op
